version: '2'
services:
    poemdata-app:
        image: poemdata
        external_links:
            - poemdata-mysql:mysql
        environment:
            - SPRING_PROFILES_ACTIVE=prod
            - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/poemdata?useUnicode=true&characterEncoding=utf8&useSSL=false
        ports:
            - 8080:8080
    poemdata-mysql:
        extends:
            file: mysql.yml
            service: poemdata-mysql
